#!/usr/bin/env bash
# This script displays the list of currently running processes
#+ It shows all processes for all users, including those which
#+ might not have a TTY
#+ Display in a user-oriented format
#+ Show process hierarchy

ps -auxf
