#!/usr/bin/env bash
# This script that displays To infinity and beyond indefinitely
#+ In between each iteration of the loop, sleep 2 is added
while true
do
	echo "To infinity and beyond"
	sleep 2
done
